import {useEffect,useState} from 'react';
import {Plus,RefreshCw,FileUp,X,ShieldCheck} from 'lucide-react';
import {api,errorText} from './api';
import DocumentPreview from './DocumentPreview';

const emptyProject={code:'',name:'',aliases:[],summary:'',phase:'planning',health:'unknown',baseline_due_date:null,planned_due_date:null,actual_delivery_date:null,blockers:[],people:[],org_visible:false};
const phases:Record<string,string>={planning:'规划',development:'开发',testing:'测试',acceptance:'验收',delivered:'已交付',paused:'暂停'};
const healths:Record<string,string>={on_track:'正常',at_risk:'有风险',delayed:'延期',unknown:'未知'};
export default function Admin({view,onError}:{view:string;onError:(s:string)=>void}){
 const[selecting,setSelecting]=useState(false),[selected,setSelected]=useState<string[]>([]),[memberSearch,setMemberSearch]=useState(''),[memberError,setMemberError]=useState('');
 const[newGroup,setNewGroup]=useState(false),[groupName,setGroupName]=useState(''),[groupError,setGroupError]=useState('');
 const[projectError,setProjectError]=useState('');
 const[preview,setPreview]=useState<any>(null);
 const[metrics,setMetrics]=useState<any>(null);
 const[tab,setTab]=useState('projects'),[projects,setProjects]=useState<any[]>([]),[docs,setDocs]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]),[feedback,setFeedback]=useState<any[]>([]);
 const[editing,setEditing]=useState<any>(null),[uploading,setUploading]=useState<any>(null),[acl,setAcl]=useState<any>(null),[publish,setPublish]=useState<any>(null),[memberGroup,setMemberGroup]=useState<any>(null),[busy,setBusy]=useState(false);
 const activeDocs=docs.filter(d=>!d.deleted_at);
 async function load(){try{if(view==='feedback'){setFeedback(await api('/admin/feedback'));return}const[p,d,g,u,j]=await Promise.all([api('/admin/projects'),api('/admin/documents'),api('/admin/groups'),api('/admin/users'),api('/admin/jobs')]);setProjects(p);setDocs(d);setSelected(ids=>ids.filter(id=>d.some((doc:any)=>doc.id===id&&!doc.deleted_at)));setGroups(g);setUsers(u);setJobs(j);setMetrics(await api('/admin/metrics'))}catch(e){onError(errorText(e))}}
 useEffect(()=>{load()},[view]);
 async function action(fn:()=>Promise<any>){setBusy(true);try{await fn();await load()}catch(e){onError(errorText(e))}finally{setBusy(false)}}
 async function changeMember(userId:string,remove:boolean){setBusy(true);setMemberError('');try{await api(`/admin/groups/${memberGroup.id}/members/${userId}`,remove?'DELETE':'PUT');const updated={...memberGroup,user_ids:remove?memberGroup.user_ids.filter((id:string)=>id!==userId):[...memberGroup.user_ids,userId]};setMemberGroup(updated);setGroups(items=>items.map(g=>g.id===updated.id?updated:g))}catch(e){setMemberError(errorText(e))}finally{setBusy(false)}}
 async function openAcl(kind:string,id:string,title:string){try{setAcl({...await api(`/admin/resources/${kind}/${id}/acl`),kind,id,title})}catch(e){onError(errorText(e))}}
 return <div className="admin-content">{view==='feedback'?<><div className="section-title"><div><h1>把问题变成改进</h1><p>反馈关联具体回答，知识更新后内容自动隐藏。</p></div><button onClick={load}><RefreshCw size={16}/>刷新</button></div>{!feedback.length?<div className="empty">暂时没有回答反馈。</div>:feedback.map(f=><article className="feedback-card" key={f.id}><div><span className="tag">{f.type}</span><small>回答 {f.run_id.slice(0,8)}</small><select value={f.state} onChange={e=>action(()=>api('/admin/feedback/'+f.id,'PATCH',{state:e.target.value}))}><option value="open">待处理</option><option value="reviewed">已查看</option><option value="resolved">已解决</option></select></div><p>{f.note||'未填写补充说明'}</p>{f.answer&&<blockquote>{f.answer.answer}</blockquote>}</article>)}</>:<>
 <div className="section-title"><div><h1>维护可靠的知识来源</h1><p>管理项目记录、文档版本与访问范围。</p></div><button onClick={load}><RefreshCw size={16}/>刷新</button></div>
 {metrics&&<p className="muted">问答并发槽位 {metrics.worker_concurrency} · 排队 {metrics.runs.queued||0} · 运行中 {metrics.runs.running||0} · 失败 {metrics.runs.failed||0}</p>}<div className="stat-row"><div><span>项目</span><strong>{projects.length}</strong></div><div><span>逻辑文档</span><strong>{docs.filter(d=>!d.deleted_at).length}</strong></div><div><span>用户组</span><strong>{groups.length}</strong></div><div><span>处理失败</span><strong>{jobs.filter(j=>j.state==='failed').length}</strong></div></div>
 <div className="tabs">{[['projects','项目记录'],['documents','文档库'],['groups','用户组'],['jobs','处理任务']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='projects'&&<><div className="table-tools"><span>{projects.length} 个项目</span><button className="primary" onClick={()=>(setProjectError(''),setEditing({...emptyProject}))}><Plus size={16}/>新增项目</button></div><div className="table-wrap"><table><thead><tr><th>项目</th><th>负责人</th><th>阶段</th><th>健康状态</th><th>操作</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.code}</small></td><td>{p.people.filter((x:any)=>x.role==='owner').map((x:any)=>x.display_name).join('、')||'未登记'}</td><td>{phases[p.phase]}</td><td><span className={'tag '+p.health}>{healths[p.health]}</span></td><td><button className="text-button" onClick={()=>(setProjectError(''),setEditing({...p}))}>编辑</button><button className="text-button" onClick={()=>openAcl('project',p.id,p.name)}>权限</button><button className="text-button danger" onClick={()=>{if(window.confirm('删除项目后将不再参与查询。关联文档会保留，但不再用于问答。确认删除？'))action(()=>api('/admin/projects/'+p.id,'DELETE'))}}>删除项目</button></td></tr>)}</tbody></table></div></>}
 {tab==='documents'&&<><div className="table-tools"><span>上传 → 解析索引 → 发布；失败不影响旧版本</span><div className="document-actions"><button disabled={busy} onClick={()=>{setSelecting(!selecting);setSelected([])}}>{selecting?'取消选择':'选择文档'}</button><button className="primary" onClick={()=>setUploading({})}><FileUp size={16}/>上传文档</button></div></div>{selecting&&<div className="table-tools"><label className="checkbox"><input type="checkbox" disabled={busy||!activeDocs.length} checked={!!activeDocs.length&&activeDocs.every(d=>selected.includes(d.id))} onChange={e=>setSelected(e.target.checked?activeDocs.map(d=>d.id):[])}/>全选已加载文档</label><span>已选择 {selected.length} 份（每次最多 1000 份）</span><button className="danger" disabled={busy||!selected.length||selected.length>1000} onClick={()=>{if(window.confirm(`确认删除选中的 ${selected.length} 份文档？删除后将无法用于问答，相关历史引用将不可访问。`))action(async()=>{await api('/admin/documents/bulk-delete','POST',{document_ids:selected});setSelected([]);setSelecting(false)})}}>删除所选文档</button></div>}{docs.length>=100&&<button onClick={async()=>{try{setDocs([...docs,...await api('/admin/documents?offset='+docs.length)])}catch(e){onError(errorText(e))}}}>加载更多文档</button>}{activeDocs.length===0&&<div className="empty">暂无文档，请上传文档。</div>}{activeDocs.map(d=><article className={'document-card '+(d.deleted_at?'deleted':'')} key={d.id}><div className="document-head"><div>{selecting&&!d.deleted_at&&<label className="checkbox"><input type="checkbox" aria-label={'选择文档：'+d.title} disabled={busy} checked={selected.includes(d.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,d.id]:ids.filter(id=>id!==d.id))}/>选择</label>}<b>{d.title}</b><small>{d.project_id||'组织制度'} · 修订 {d.revision}</small></div>{!d.deleted_at?<div><button onClick={()=>setPreview(d)}>查看内容</button><button onClick={()=>setUploading(d)}>新版本</button><button onClick={()=>openAcl('document',d.id,d.title)}><ShieldCheck size={14}/>权限</button><button className="danger" onClick={()=>{if(window.confirm('删除后资料立即不可查询，旧会话会失效。确认删除？'))action(()=>api('/admin/documents/'+d.id,'DELETE'))}}>删除</button></div>:<span className="tag">已删除</span>}</div>{d.versions.map((v:any)=><div className="version-row" key={v.id}><span>{v.version_label}</span><span className="tag">{v.processing}</span><span>{v.publication}</span>{v.error_code&&<span className="danger">{v.error_code}</span>}{!d.deleted_at&&v.processing==='ready'&&v.publication==='draft'&&<button onClick={()=>setPublish({id:v.id,revision:d.revision,title:d.title})}>发布</button>}{!d.deleted_at&&v.processing==='failed'&&<button onClick={()=>action(()=>api('/admin/versions/'+v.id+'/retry','POST'))}>重试</button>}</div>)}</article>)}</>}
 {tab==='groups'&&<><div className="table-tools"><span>{groups.length} 个用户组</span><button className="primary" onClick={()=>{setNewGroup(true);setGroupName('');setGroupError('')}}><Plus size={16}/>增加用户组</button></div><div className="group-grid">{groups.map(g=><article key={g.id}><h3>{g.name}</h3><p>{users.filter(u=>g.user_ids.includes(u.id)).map(u=>u.display_name).join('、')||'暂无成员'}</p><button onClick={()=>{setMemberGroup({...g});setMemberSearch('');setMemberError('')}}>管理员工</button><button className="danger" disabled={busy} onClick={()=>{if(window.confirm(`确定删除用户组“${g.name}”？将移除该组的成员关系和项目/文档授权，不会删除用户账号。`))action(()=>api('/admin/groups/'+g.id,'DELETE'))}}>删除用户组</button></article>)}</div></>}
 {tab==='jobs'&&<div className="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>尝试次数</th><th>错误 / 操作</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>{j.kind}<small>{j.target_id.slice(0,12)}</small></td><td>{j.state}</td><td>{j.attempts}</td><td>{j.error_code||'—'}{j.kind==='cleanup'&&j.state==='failed'&&<button onClick={()=>action(()=>api('/admin/jobs/'+j.id+'/retry','POST'))}>重试清理</button>}</td></tr>)}</tbody></table></div>}
 </>}
 {preview&&<DocumentPreview document={preview} close={()=>setPreview(null)}/>}
 {editing&&<Modal title={editing.id?'编辑项目':'新增项目'} close={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();action(async()=>{setProjectError('');const{id,updated_at,...body}=editing;try{await api('/admin/projects'+(id?'/'+id:''),id?'PATCH':'POST',body);setEditing(null)}catch(e){setProjectError(errorText(e));throw e}})}}><div className="form-grid"><label>项目编号<input required maxLength={40} value={editing.code} onChange={e=>setEditing({...editing,code:e.target.value})}/></label><label>项目名称<input required maxLength={100} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>阶段<select value={editing.phase} onChange={e=>setEditing({...editing,phase:e.target.value})}>{Object.entries(phases).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>健康状态<select value={editing.health} onChange={e=>setEditing({...editing,health:e.target.value})}>{Object.entries(healths).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{[['baseline_due_date','基线日期'],['planned_due_date','计划日期'],['actual_delivery_date','实际交付日期']].map(([k,l])=><label key={k}>{l}<input type="date" value={editing[k]||''} onChange={e=>setEditing({...editing,[k]:e.target.value||null})}/></label>)}</div><label>项目简要情况<textarea value={editing.summary||''} maxLength={4000} placeholder="介绍项目背景、目标、范围及目前的简要情况" onChange={e=>setEditing({...editing,summary:e.target.value})}/></label><label>阻塞事项（每行一项）<textarea value={editing.blockers.join('\n')} onChange={e=>setEditing({...editing,blockers:e.target.value.split('\n')})}/></label><label>人员角色</label>{editing.people.map((person:any,i:number)=><div className="person-row" key={i}><input aria-label="人员姓名" placeholder="姓名" value={person.display_name} onChange={e=>setEditing({...editing,people:editing.people.map((p:any,n:number)=>n===i?{...p,display_name:e.target.value}:p)})}/><select aria-label="人员角色" value={person.role} onChange={e=>setEditing({...editing,people:editing.people.map((p:any,n:number)=>n===i?{...p,role:e.target.value}:p)})}><option value="owner">负责人</option><option value="qa">测试</option><option value="delivery">交付</option><option value="member">成员</option></select><button type="button" onClick={()=>setEditing({...editing,people:editing.people.filter((_:any,n:number)=>n!==i)})}><X size={15}/></button></div>)}<button type="button" onClick={()=>setEditing({...editing,people:[...editing.people,{display_name:'',role:'owner'}]})}>添加人员</button><label className="checkbox"><input type="checkbox" checked={editing.org_visible} onChange={e=>setEditing({...editing,org_visible:e.target.checked})}/>组织内可见</label>{projectError&&<p role="alert" className="error">{projectError}</p>}<button className="primary" disabled={busy}>保存项目</button></form></Modal>}
 {uploading&&<Modal title={uploading.id?'上传新版本':'上传文档'} close={()=>setUploading(null)}><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);action(async()=>{await api('/admin/documents'+(uploading.id?'/'+uploading.id+'/versions':''),'POST',data);setUploading(null)})}}>{!uploading.id&&<><label>文档标题<input name="title" required maxLength={200}/></label><label>所属项目<select name="project_id"><option value="">组织制度（无项目）</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label></>}<label>版本名称<input name="version_label" required maxLength={80} defaultValue={uploading.id?'':'v1'}/></label><label>文件<input type="file" name="file" accept=".md,.txt,.pdf" required/></label><p className="muted">最大 10 MiB，PDF 最多 100 页。暂不支持扫描件和 DOCX。新文档默认仅管理员可见，发布后请设置权限。</p><button className="primary" disabled={busy}>上传并处理</button></form></Modal>}
 {acl&&<Modal title={'访问范围 · '+acl.title} close={()=>setAcl(null)}><form onSubmit={e=>{e.preventDefault();action(async()=>{await api(`/admin/resources/${acl.kind}/${acl.id}/acl`,'PUT',{org_visible:acl.org_visible,grants:acl.grants});setAcl(null)})}}><label className="checkbox"><input type="checkbox" checked={acl.org_visible} onChange={e=>setAcl({...acl,org_visible:e.target.checked})}/>组织内可见</label><p className="muted">关联项目文档还须同时满足项目访问权限。历史会话保留；撤销权限后相关回答将隐藏。</p>{[...groups.map(g=>({...g,label:g.name,kind:'group'})),...users.map(u=>({...u,label:u.display_name,kind:'user'}))].map(s=><label className="checkbox" key={s.kind+s.id}><input type="checkbox" checked={acl.grants.some((g:any)=>g.subject_type===s.kind&&g.subject_id===s.id)} onChange={e=>setAcl({...acl,grants:e.target.checked?[...acl.grants,{subject_type:s.kind,subject_id:s.id}]:acl.grants.filter((g:any)=>!(g.subject_type===s.kind&&g.subject_id===s.id))})}/>{s.kind==='group'?'用户组':'用户'} · {s.label}</label>)}<button className="primary" disabled={busy}>保存权限</button></form></Modal>}
 {publish&&<Modal title={'发布 · '+publish.title} close={()=>setPublish(null)}><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);action(async()=>{await api('/admin/versions/'+publish.id+'/publish','POST',{revision:publish.revision,effective_from:new Date(String(data.get('from'))).toISOString(),effective_to:data.get('to')?new Date(String(data.get('to'))).toISOString():null});setPublish(null)})}}><label>生效时间<input type="datetime-local" name="from" required defaultValue="2026-09-12T00:00"/></label><label>失效时间（可留空）<input type="datetime-local" name="to"/></label><p className="muted">发布会结束覆盖区间内的旧版本，历史回答会保留并标记知识更新。</p><button className="primary" disabled={busy}>发布版本</button></form></Modal>}
 {newGroup&&<Modal title="增加用户组" close={()=>setNewGroup(false)}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setGroupError('');try{await api('/admin/groups','POST',{name:groupName.trim()});setNewGroup(false);await load()}catch(e){setGroupError(errorText(e))}finally{setBusy(false)}}}><label>用户组名称<input autoFocus required maxLength={100} value={groupName} onChange={e=>setGroupName(e.target.value)}/></label><p className="muted">创建后可维护成员，并在项目或文档的权限设置中授权给该组。</p>{groupError&&<p role="alert" className="error">{groupError}</p>}<button className="primary" disabled={busy||!groupName.trim()}>保存用户组</button></form></Modal>}
 {memberGroup&&<Modal title={'员工管理 · '+memberGroup.name} close={()=>{if(!busy)setMemberGroup(null)}}><p className="muted">添加或移除后立即生效。移除仅解除该组成员关系，不删除员工账号。</p><label>搜索员工<input placeholder="姓名或用户名" value={memberSearch} onChange={e=>setMemberSearch(e.target.value)}/></label>{memberError&&<p role="alert" className="error">{memberError}</p>}{[true,false].map(isMember=><section key={String(isMember)}><h4>{isMember?'组内员工':'可添加员工'}</h4>{users.filter(u=>memberGroup.user_ids.includes(u.id)===isMember&&`${u.display_name} ${u.username}`.toLowerCase().includes(memberSearch.trim().toLowerCase())).map(u=><div className="member-row" key={u.id}><span>{u.display_name}<small>{u.username} · {u.role==='admin'?'管理员':'员工'}</small></span><button disabled={busy} className={isMember?'danger':''} aria-label={`${isMember?'移除':'添加'}员工：${u.username}`} onClick={()=>changeMember(u.id,isMember)}>{isMember?'移出用户组':'添加到用户组'}</button></div>)}{!users.some(u=>memberGroup.user_ids.includes(u.id)===isMember&&`${u.display_name} ${u.username}`.toLowerCase().includes(memberSearch.trim().toLowerCase()))&&<p className="muted">暂无匹配员工</p>}</section>)}</Modal>}
 </div>
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="panel-head"><h3>{title}</h3><button onClick={close} aria-label="关闭"><X size={18}/></button></div>{children}</div></div>}
